openapi: 3.0.0
info:
  title: Football Championship Central API
  description: API for managing championships, teams, players, matches, seasons, rankings, and statistics.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /championships:
    get:
      summary: Retrieve all championships
      parameters:
        - name: year
          in: query
          description: Filter championships by year
          required: false
          schema:
            type: integer
            example: 2024
        - name: name
          in: query
          description: Filter championships by name
          required: false
          schema:
            type: string
            example: "La Liga"
      responses:
        '200':
          description: A list of championships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Championship'
    post:
      summary: Add a new championship
      parameters:
        - name: notifyTeams
          in: query
          description: Whether to notify teams about the new championship
          required: false
          schema:
            type: boolean
            example: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Championship'
      responses:
        '200':
          description: Championship added successfully
        '500':
          description: Error adding championship

  /clubs:
    get:
      summary: Retrieve all clubs
      parameters:
        - name: city
          in: query
          description: Filter clubs by city
          required: false
          schema:
            type: string
            example: "Barcelona"
        - name: name
          in: query
          description: Filter clubs by name
          required: false
          schema:
            type: string
            example: "Real Madrid"
        - name: active
          in: query
          description: Filter clubs by their activity status (active or inactive)
          required: false
          schema:
            type: boolean
            example: false
      responses:
        '200':
          description: A list of clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
    post:
      summary: Add a new club
      parameters:
        - name: notifyPlayers
          in: query
          description: Whether to notify players about the new club
          required: false
          schema:
            type: boolean
            example: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Club'
      responses:
        '200':
          description: Club added successfully
        '500':
          description: Error adding club

  /coaches:
    post:
      summary: Add a new coach
      parameters:
        - name: notify
          in: query
          description: Whether to notify the coach about their addition
          required: false
          schema:
            type: boolean
            example: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coach'
      responses:
        '200':
          description: Coach added successfully
        '500':
          description: Error adding coach

  /matches:
    get:
      summary: Retrieve all matches
      parameters:
        - name: date
          in: query
          description: Filter matches by date
          required: false
          schema:
            type: string
            format: date
            example: "2024-06-01"
      responses:
        '200':
          description: A list of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
    post:
      summary: Add a new match
      parameters:
        - name: notifyTeams
          in: query
          description: Whether to notify teams about the new match
          required: false
          schema:
            type: boolean
            example: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
      responses:
        '200':
          description: Match added successfully
        '500':
          description: Error adding match

  /players:
    get:
      summary: Retrieve all players
      parameters:
        - name: club
          in: query
          description: Filter players by club name
          required: false
          schema:
            type: string
            example: "Real Madrid"
        - name: name
          in: query
          description: Filter players by name
          required: false
          schema:
            type: string
            example: "Karim Benzema"
        - name: ageMin
          in: query
          description: Minimum age filter
          required: false
          schema:
            type: integer
            example: 20
        - name: ageMax
          in: query
          description: Maximum age filter
          required: false
          schema:
            type: integer
            example: 40
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      summary: Add a new player
      parameters:
        - name: notify
          in: query
          description: Whether to notify the player about their addition
          required: false
          schema:
            type: boolean
            example: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: Player added successfully
        '500':
          description: Error adding the player

  /seasons:
    get:
      summary: Retrieve all seasons
      parameters:
        - name: includeInactive
          in: query
          description: Whether to include inactive seasons
          required: false
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: A list of seasons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Season'
    post:
      summary: Add a new season
      parameters:
        - name: notifyTeams
          in: query
          description: Whether to notify teams about the new season
          required: false
          schema:
            type: boolean
            example: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Season'
      responses:
        '200':
          description: Season added successfully
        '500':
          description: Error adding the season

components:
  schemas:
    Championship:
      type: object
      properties:
        name:
          type: string
          example: "La Liga"
        year:
          type: integer
          example: 2024

    Club:
      type: object
      properties:
        name:
          type: string
          example: "FC Barcelona"
        location:
          type: string
          example: "Barcelona, Spain"

    Coach:
      type: object
      properties:
        name:
          type: string
          example: "Xavi Hernandez"
        experience:
          type: integer
          example: 5  # Years of coaching experience

    Match:
      type: object
      properties:
        homeTeam:
          type: string
          example: "Atletico Madrid"
        awayTeam:
          type: string
          example: "Sevilla"
        date:
          type: string
          format: date
          example: "2024-06-01"

    Player:
      type: object
      properties:
        name:
          type: string
          example: "Ansu Fati"
        team:
          type: string
          example: "FC Barcelona"
        position:
          type: string
          example: "Forward"
        age:
          type: integer
          example: 21

    Season:
      type: object
      properties:
        year:
          type: integer
          example: 2024
        champion:
          type: string
          example: "FC Barcelona"