openapi: 3.0.0
info:
  title: Football Championship Management API
  description: API for managing championships, teams, players, matches, seasons, rankings, and statistics.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /players:
    get:
      summary: Retrieve all players
      parameters:
        - name: club
          in: query
          description: Filter players by club name
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: Filter players by name
          required: false
          schema:
            type: string
        - name: ageMin
          in: query
          description: Minimum age filter
          required: false
          schema:
            type: integer
        - name: ageMax
          in: query
          description: Maximum age filter
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error
    put:
      summary: Update a player
      parameters:
        - name: id
          in: query
          description: ID of the player to update
          required: true
          schema:
            type: string
        - name: notify
          in: query
          description: Whether to notify the player about the update
          required: false
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerUpdate'
      responses:
        '200':
          description: Player updated successfully
        '400':
          description: Invalid data
        '404':
          description: Player not found
        '500':
          description: Internal server error

  /seasons:
    get:
      summary: Retrieve all seasons
      parameters:
        - name: includeInactive
          in: query
          description: Whether to include inactive seasons
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: List of seasons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Season'
        '500':
          description: Internal server error
    post:
      summary: Add a new season
      parameters:
        - name: notifyTeams
          in: query
          description: Whether to notify all teams about the new season
          required: false
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Season'
      responses:
        '201':
          description: Season created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Season'
        '400':
          description: Invalid data
        '500':
          description: Internal server error

  /seasons/{seasonYear}/status:
    put:
      summary: Update the status of a season
      parameters:
        - name: seasonYear
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  example: "FINISHED"
      responses:
        '200':
          description: Season status updated successfully
        '404':
          description: Season not found
        '400':
          description: Invalid data

  /clubs:
    get:
      summary: Retrieve all clubs
      parameters:
        - name: city
          in: query
          description: Filter clubs by city
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: Filter clubs by name
          required: false
          schema:
            type: string
        - name: active
          in: query
          description: Filter clubs by their activity status (active or inactive)
          required: false
          schema:
            type: boolean
        - name: minPlayers
          in: query
          description: Filter clubs by minimum number of players
          required: false
          schema:
            type: integer
            example: 11  # Example of a club with at least 11 players
      responses:
        '200':
          description: List of clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
        '500':
          description: Internal server error
    put:
      summary: Update a club
      parameters:
        - name: id
          in: query
          description: ID of the club to update
          required: true
          schema:
            type: string
        - name: notifyPlayers
          in: query
          description: Whether to notify all players in the club about the update
          required: false
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Club'
      responses:
        '200':
          description: Club updated successfully
        '400':
          description: Invalid data
        '404':
          description: Club not found
        '500':
          description: Internal server error

components:
  schemas:
    Player:
      type: object
      required:
        - name
        - number
        - position
        - nationality
        - age
      properties:
        id:
          type: string
        name:
          type: string
        number:
          type: integer
        position:
          type: string
        nationality:
          type: string
        age:
          type: integer

    PlayerUpdate:
      type: object
      properties:
        name:
          type: string
        number:
          type: integer
        position:
          type: string
        nationality:
          type: string
        age:
          type: integer

    Club:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        city:
          type: string

    Season:
      type: object
      required:
        - name
        - startDate
        - endDate
      properties:
        id:
          type: string
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    Match:
      type: object
      properties:
        id:
          type: string
        homeTeam:
          type: string
        awayTeam:
          type: string
        date:
          type: string
          format: date-time
        status:
          type: string

    Statistics:
      type: object
      properties:
        goals:
          type: integer
        assists:
          type: integer
        yellowCards:
          type: integer
        redCards:
          type: integer

    ClubStatistics:
      type: object
      properties:
        teamName:
          type: string
        matchesPlayed:
          type: integer
        goalsScored:
          type: integer
        goalsConceded:
          type: integer
        winPercentage:
          type: number
          format: float
