openapi: 3.0.0
info:
  title: Football Championship Management API
  description: API for managing championships, teams, players, matches, seasons, rankings, and statistics.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /players:
    get:
      summary: Retrieve all players
      parameters:
        - name: club
          in: query
          description: Filter players by club name
          required: false
          schema:
            type: string
            example: "FC Barcelona"  # Example of club name
        - name: name
          in: query
          description: Filter players by name
          required: false
          schema:
            type: string
            example: "Lionel Messi"  # Example of player name
        - name: ageMin
          in: query
          description: Minimum age filter
          required: false
          schema:
            type: integer
            example: 18  # Example of minimum age
        - name: ageMax
          in: query
          description: Maximum age filter
          required: false
          schema:
            type: integer
            example: 40  # Example of maximum age
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error
    put:
      summary: Update a player
      parameters:
        - name: id
          in: query
          description: ID of the player to update
          required: true
          schema:
            type: string
            example: "12345"  # Example player ID
        - name: notify
          in: query
          description: Whether to notify the player about the update
          required: false
          schema:
            type: boolean
            example: true  # Example of notification preference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerUpdate'
      responses:
        '200':
          description: Player updated successfully
        '400':
          description: Invalid data
        '404':
          description: Player not found
        '500':
          description: Internal server error

  /seasons:
    get:
      summary: Retrieve all seasons
      parameters:
        - name: includeInactive
          in: query
          description: Whether to include inactive seasons
          required: false
          schema:
            type: boolean
            example: false  # Example of including inactive seasons
      responses:
        '200':
          description: List of seasons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Season'
        '500':
          description: Internal server error
    post:
      summary: Add a new season
      parameters:
        - name: notifyTeams
          in: query
          description: Whether to notify all teams about the new season
          required: false
          schema:
            type: boolean
            example: true  # Example of notifying teams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Season'
      responses:
        '201':
          description: Season created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Season'
        '400':
          description: Invalid data
        '500':
          description: Internal server error

  /seasons/{seasonYear}/status:
    put:
      summary: Update the status of a season
      parameters:
        - name: seasonYear
          in: path
          required: true
          schema:
            type: string
            example: "2024"  # Example of season year
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  example: "FINISHED"  # Example of status
      responses:
        '200':
          description: Season status updated successfully
        '404':
          description: Season not found
        '400':
          description: Invalid data

  /clubs:
    get:
      summary: Retrieve all clubs
      parameters:
        - name: city
          in: query
          description: Filter clubs by city
          required: false
          schema:
            type: string
            example: "Madrid"  # Example of city filter
        - name: name
          in: query
          description: Filter clubs by name
          required: false
          schema:
            type: string
            example: "FC Barcelona"  # Example of club name
        - name: active
          in: query
          description: Filter clubs by their activity status (active or inactive)
          required: false
          schema:
            type: boolean
            example: true  # Example of active clubs
        - name: minPlayers
          in: query
          description: Filter clubs by minimum number of players
          required: false
          schema:
            type: integer
            example: 11  # Example of a club with at least 11 players
      responses:
        '200':
          description: List of clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
        '500':
          description: Internal server error
    put:
      summary: Update a club
      parameters:
        - name: id
          in: query
          description: ID of the club to update
          required: true
          schema:
            type: string
            example: "67890"  # Example club ID
        - name: notifyPlayers
          in: query
          description: Whether to notify all players in the club about the update
          required: false
          schema:
            type: boolean
            example: true  # Example of notification preference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Club'
      responses:
        '200':
          description: Club updated successfully
        '400':
          description: Invalid data
        '404':
          description: Club not found
        '500':
          description: Internal server error

  /players/{id}/statistics/{seasonYear}:
    get:
      summary: Retrieve statistics for a player in a given season
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "12345"  # Example player ID
        - name: seasonYear
          in: path
          required: true
          schema:
            type: string
            example: "2024"  # Example season year
      responses:
        '200':
          description: Player statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
        '404':
          description: Player or season not found
        '500':
          description: Internal server error

  /clubs/{id}/players:
    get:
      summary: Retrieve all players for a specific club
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "67890"  # Example club ID
      responses:
        '200':
          description: List of players in the club
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '404':
          description: Club not found
        '500':
          description: Internal server error

  /clubs/statistics/{seasonYear}:
    get:
      summary: Retrieve statistics for all clubs in a given season
      parameters:
        - name: seasonYear
          in: path
          required: true
          schema:
            type: string
            example: "2024"  # Example season year
      responses:
        '200':
          description: Club statistics retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClubStatistics'
        '404':
          description: Season not found
        '500':
          description: Internal server error

components:
  schemas:
    Player:
      type: object
      required:
        - name
        - number
        - position
        - nationality
        - age
      properties:
        id:
          type: string
        name:
          type: string
          example: "Lionel Messi"  # Example player name
        number:
          type: integer
          example: 10  # Example player number
        position:
          type: string
          example: "Forward"  # Example position
        nationality:
          type: string
          example: "Argentinian"  # Example nationality
        age:
          type: integer
          example: 34  # Example age

    PlayerUpdate:
      type: object
      properties:
        name:
          type: string
          example: "Lionel Messi"
        number:
          type: integer
          example: 10
        position:
          type: string
          example: "Forward"
        nationality:
          type: string
          example: "Argentinian"
        age:
          type: integer
          example: 34

    Club:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: "FC Barcelona"
        city:
          type: string
          example: "Barcelona"  # Example city

    Season:
      type: object
      required:
        - name
        - startDate
        - endDate
      properties:
        id:
          type: string
        name:
          type: string
          example: "Saison 2024-2025"  # Example season name
        startDate:
          type: string
          format: date
          example: "2024-09-01"  # Example start date
        endDate:
          type: string
          format: date
          example: "2025-06-30"  # Example end date

    Match:
      type: object
      properties:
        id:
          type: string
          example: "match_001"  # Example match ID
        homeTeam:
          type: string
          example: "Real Madrid"  # Example home team
        awayTeam:
          type: string
          example: "FC Barcelona"  # Example away team
        date:
          type: string
          format: date-time
          example: "2025-05-01T21:00:00Z"  # Example match date
        status:
          type: string
          example: "Scheduled"  # Example status

    Statistics:
      type: object
      properties:
        goals:
          type: integer
          example: 10  # Example goals
        assists:
          type: integer
          example: 5  # Example assists
        yellowCards:
          type: integer
          example: 2  # Example yellow cards
        redCards:
          type: integer
          example: 1  # Example red cards

    ClubStatistics:
      type: object
      properties:
        teamName:
          type: string
          example: "FC Barcelona"  # Example team name
        matchesPlayed:
          type: integer
          example: 38  # Example matches played
        goalsScored:
          type: integer
          example: 90  # Example goals scored
        goalsConceded:
          type: integer
          example: 30  # Example goals conceded
        winPercentage:
          type: number
          format: float
          example: 0.75  # Example win percentage
