openapi: 3.0.0
info:
  title: Football Championship Management API
  description: API for managing championships, teams, players, matches, seasons, rankings, and statistics.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /players:
    get:
      summary: Retrieve all players
      parameters:
        - name: club
          in: query
          description: Filter players by club ID
          required: false
          schema:
            type: string
            example: "1"
        - name: name
          in: query
          description: Filter players by name
          required: false
          schema:
            type: string
            example: "Lionel Messi"
        - name: ageMin
          in: query
          description: Minimum age filter
          required: false
          schema:
            type: integer
            example: 18
        - name: ageMax
          in: query
          description: Maximum age filter
          required: false
          schema:
            type: integer
            example: 40
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error
    post:
      summary: Add a new player
      parameters:
        - name: clubId
          in: query
          description: ID of the club the player belongs to
          required: true
          schema:
            type: string
            example: "1"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - number
                - age
                - position
                - nationality
                - status
              properties:
                name:
                  type: string
                  example: "Lionel Messi"
                number:
                  type: integer
                  example: 10
                age:
                  type: integer
                  example: 34
                position:
                  type: string
                  example: "Forward"
                nationality:
                  type: string
                  example: "Argentinian"
                status:
                  type: string
                  example: "ACTIVE"  # Status of the player (ACTIVE, INJURED, etc.)
      responses:
        '201':
          description: Player created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '400':
          description: Invalid data
        '500':
          description: Internal server error

  /seasons:
    get:
      summary: Retrieve all seasons
      parameters:
        - name: includeInactive
          in: query
          description: Include inactive seasons in the response
          required: false
          schema:
            type: boolean
            example: false
      responses:
        '200':
          description: List of seasons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Season'
        '500':
          description: Internal server error
    post:
      summary: Add a new season
      parameters:
        - name: notifyTeams
          in: query
          description: Whether to notify teams about the new season
          required: false
          schema:
            type: boolean
            example: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - startDate
                - endDate
                - status
              properties:
                name:
                  type: string
                  example: "Season 2024-2025"
                startDate:
                  type: string
                  format: date
                  example: "2024-09-01"
                endDate:
                  type: string
                  format: date
                  example: "2025-06-30"
                status:
                  type: string
                  example: "ACTIVE"  # Current status of the season (ACTIVE, INACTIVE)
      responses:
        '201':
          description: Season created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Season'
        '400':
          description: Invalid data
        '500':
          description: Internal server error

  /clubs:
    get:
      summary: Retrieve all clubs
      parameters:
        - name: city
          in: query
          description: Filter clubs by city
          required: false
          schema:
            type: string
            example: "Barcelona"
        - name: active
          in: query
          description: Filter clubs by their activity status
          required: false
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: List of clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
        '500':
          description: Internal server error
    post:
      summary: Add a new club
      parameters:
        - name: homeClub
          in: query
          description: Home club for the new club
          required: false
          schema:
            type: string
            example: "Home Club"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - acronym
                - yearFounded
                - stadium
                - coach
                - nationality
                - status
              properties:
                name:
                  type: string
                  example: "FC Barcelona"
                acronym:
                  type: string
                  example: "FCB"
                yearFounded:
                  type: integer
                  example: 1899
                stadium:
                  type: string
                  example: "Camp Nou"
                coach:
                  type: string
                  example: "Xavi Hernandez"
                nationality:
                  type: string
                  example: "Spanish"
                awayClub:
                  type: string
                  example: "Away Club"
                status:
                  type: string
                  example: "ACTIVE"  # Current status of the club (ACTIVE, INACTIVE)
      responses:
        '201':
          description: Club created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Club'
        '400':
          description: Invalid data
        '500':
          description: Internal server error

  /clubs/{id}:
    put:
      summary: Update a club
      parameters:
        - name: id
          in: path
          description: ID of the club to update
          required: true
          schema:
            type: string
            example: "1"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Club'
      responses:
        '200':
          description: Club updated successfully
        '400':
          description: Invalid data
        '404':
          description: Club not found
        '500':
          description: Internal server error

  /clubs/{id}/players:
    get:
      summary: Retrieve all players for a specific club
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "2"
      responses:
        '200':
          description: List of players in the club
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '404':
          description: Club not found
        '500':
          description: Internal server error

  /clubs/statistics/{seasonYear}:
    get:
      summary: Retrieve statistics for all clubs in a given season
      parameters:
        - name: seasonYear
          in: path
          required: true
          schema:
            type: string
            example: "2024"
      responses:
        '200':
          description: Club statistics retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClubStatistics'
        '404':
          description: Season not found
        '500':
          description: Internal server error

components:
  schemas:
    Player:
      type: object
      required:
        - name
        - number
        - position
        - nationality
        - age
      properties:
        id:
          type: string
        name:
          type: string
          example: "Lionel Messi"
        number:
          type: integer
          example: 10
        position:
          type: string
          example: "Forward"
        nationality:
          type: string
          example: "Argentinian"
        age:
          type: integer
          example: 34
        status:
          type: string
          example: "ACTIVE"  # Status of the player

    PlayerUpdate:
      type: object
      properties:
        name:
          type: string
          example: "Lionel Messi"
        number:
          type: integer
          example: 10
        position:
          type: string
          example: "Forward"
        nationality:
          type: string
          example: "Argentinian"
        age:
          type: integer
          example: 34

    Club:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: "FC Barcelona"
        acronym:
          type: string
          example: "FCB"
        yearFounded:
          type: integer
          example: 1899
        stadium:
          type: string
          example: "Camp Nou"
        coach:
          type: string
          example: "Xavi Hernandez"
        nationality:
          type: string
          example: "Spanish"
        homeClub:
          type: string
          example: "Home Club"
        awayClub:
          type: string
          example: "Away Club"
        status:
          type: string
          example: "ACTIVE"  # Status of the club

    Season:
      type: object
      required:
        - name
        - startDate
        - endDate
        - status
      properties:
        id:
          type: string
        name:
          type: string
          example: "Season 2024-2025"
        startDate:
          type: string
          format: date
          example: "2024-09-01"
        endDate:
          type: string
          format: date
          example: "2025-06-30"
        notifyTeams:
          type: boolean
          example: true  # Whether to notify all teams about the new season
        status:
          type: string
          example: "ACTIVE"  # Current status of the season

    IndividualStatistics:
      type: object
      properties:
        goals:
          type: integer
          example: 10
        assists:
          type: integer
          example: 5
        yellowCards:
          type: integer
          example: 2
        redCards:
          type: integer
          example: 1

    ClubStatistics:
      type: object
      properties:
        teamName:
          type: string
          example: "FC Barcelona"
        matchesPlayed:
          type: integer
          example: 38
        goalsScored:
          type: integer
          example: 90
        goalsConceded:
          type: integer
          example: 30
        winPercentage:
          type: number
          format: float
          example: 0.75